export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as Bills } from './Bills'
export { default as Invoices } from './Invoices'
export { default as Resources } from './Resources'
export { default as Analysis } from './Analysis'
export { default as Support } from './Support'
